controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  robot_state_controller:
    type: robot_state_controller/RobotStateController
    publish_rate: 100

  trigger_calibration_controller:
    type: rm_calibration_controllers/MechanicalCalibrationController
    actuator: [ trigger_joint_motor ]
    velocity:
      search_velocity: 4.0
      vel_threshold: 0.001
      joint: trigger_joint
      pid: { p: 0.8, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true }

  pitch_calibration_controller:
    type: rm_calibration_controllers/MechanicalCalibrationController
    actuator: [ pitch_joint_motor ]
    velocity:
      search_velocity: 4.5
      vel_threshold: 0.001
      joint: pitch_joint
      pid: { p: 0.3, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true }

  yaw_calibration_controller:
    type: rm_calibration_controllers/GpioCalibrationController
    actuator: [ yaw_joint_motor ]
    gpio: "yaw"
    initial_gpio_state: false
    velocity:
      search_velocity: 4.5
      slow_forward_velocity: 2.0
      joint: yaw_joint
      pid: { p: 0.32, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true }
    position:
      pos_threshold: 0.05
      backward_angle: 0.2
      joint: yaw_joint
      pid: { p: 20.0, i: 0, d: 0.8, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true }

  chassis_controller:
    type: rm_chassis_controllers/OmniController
    # ChassisBase
    publish_rate: 100
    enable_odom_tf: true
    publish_odom_tf: false
    power:
      effort_coeff: 2.4
      vel_coeff: 0.008
      power_offset: -9.8
    yaw_vel:
      k_yaw_vel: 0.0
    twist_angular: 0.5233
    timeout: 0.1
    pid_follow: { p: 8.0, i: 0, d: 0.02, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    twist_covariance_diagonal: [ 0.001, 0.001, 0.001, 0.001, 0.001, 0.001 ]

    # OmniController
    wheels:
      left_front:
        pose: [ 0.145877, 0.1425, 0. ]
        roller_angle: -0.785
        joint: left_front_wheel_joint
        <<: &wheel_setting
          radius: 0.07625
          pid: { p: 0.6, i: 0.01, d: 0.0, i_max: 0.1, i_min: 0.1, antiwindup: true, publish_state: true }
      right_front:
        pose: [ 0.145877, -0.1425, 0. ]
        roller_angle: 0.785
        joint: right_front_wheel_joint
        <<: *wheel_setting
      left_back:
        pose: [ -0.149123, 0.1425, 0. ]
        roller_angle: 0.785
        joint: left_back_wheel_joint
        <<: *wheel_setting
      right_back:
        pose: [ -0.149123, -0.1425, 0. ]
        roller_angle: -0.785
        joint: right_back_wheel_joint
        <<: *wheel_setting

  orientation_controller:
    type: rm_orientation_controller/Controller
    publish_rate: 100
    name: "gimbal_imu"
    frame_source: "odom"
    frame_target: "base_link"

  gimbal_controller:
    type: rm_gimbal_controllers/Controller
    yaw:
      joint: "yaw_joint"
      pid: { p: 30.0, i: 0.0, d: 1.5, i_clamp_max: 0.1, i_clamp_min: -0.1, antiwindup: true, publish_state: true }
      k_chassis_vel: 0.05
      resistance_compensation:
        resistance: 0.0
        error_tolerance: 0.0
    pitch:
      joint: "pitch_joint"
      pid: { p: 60.0, i: 0, d: 2.5, i_clamp_max: 0, i_clamp_min: 0, antiwindup: true, publish_state: true }
    imu_name: "gimbal_imu"
    feedforward:
      gravity: 0.0
      enable_gravity_compensation: false
      mass_origin: [ 0.0,0.0,0.0 ]
    bullet_solver:
      resistance_coff_qd_10: 0.0
      resistance_coff_qd_15: 1.0
      resistance_coff_qd_16: 0.0
      resistance_coff_qd_18: 0.55
      resistance_coff_qd_30: 3.0
      g: 9.81
      delay: 0.1
      dt: 0.001
      timeout: 0.001
      publish_rate: 50
    chassis_vel:
      num_data: 20
      debug: true

  shooter_controller:
    type: rm_shooter_controllers/Controller
    publish_rate: 50
    friction_left:
      joint: "left_friction_wheel_joint"
      pid: { p: 0.001, i: 0.01, d: 0.0, i_clamp_max: 0.01, i_clamp_min: -0.01, antiwindup: true, publish_state: true }
    friction_right:
      joint: "right_friction_wheel_joint"
      pid: { p: 0.001, i: 0.01, d: 0.0, i_clamp_max: 0.01, i_clamp_min: -0.01, antiwindup: true, publish_state: true }
    trigger:
      joint: "trigger_joint"
      pid: { p: 57.0, i: 0.0, d: 1.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true, publish_state: true }
    push_per_rotation: 5
    push_qd_threshold: 0.85
    block_effort: 5.0
    block_speed: 0.1
    block_duration: 0.05
    block_overtime: 0.5
    anti_block_angle: 0.43
    anti_block_threshold: 0.1
    forward_push_threshold: 0.2
    exit_push_threshold: 0.23
