controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  robot_state_controller:
    type: robot_state_controller/RobotStateController
    publish_rate: 100

  chassis_controller:
    type: rm_chassis_controllers/OmniController
    # ChassisBase
    publish_rate: 100
    enable_odom_tf: true
    publish_odom_tf: true
    command_source_frame: "base_link"
    power:
      effort_coeff: 1.9
      vel_coeff: 0.0040
      power_offset: -8.41
    twist_angular: 0.5233
    timeout: 0.1
    pid_follow: { p: 5.0, i: 0, d: 0.3, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    twist_covariance_diagonal: [ 0.001, 0.001, 0.001, 0.001, 0.001, 0.001 ]

    # OmniController
    wheels:
      left_front:
        pose: [ 0.147, 0.147, 2.356 ]
        joint: left_front_wheel_joint
        <<: &wheel_setting
          roller_angle: 0.
          radius: 0.07625
          pid: { p: 0.41, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
      right_front:
        pose: [ 0.147, -0.147, 0.785 ]
        joint: right_front_wheel_joint
        <<: *wheel_setting
      left_back:
        pose: [ -0.147, 0.147, -2.356 ]
        joint: left_back_wheel_joint
        <<: *wheel_setting
      right_back:
        pose: [ -0.147, -0.147, -0.785 ]
        joint: right_back_wheel_joint
        <<: *wheel_setting