base_local_planner: "dwa_local_planner/DWAPlannerROS"

controller_frequency: 20

DWAPlannerROS:
  odom_topic: state_estimation
  holonomic_robot: true

  # Tolerance 
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.05
  latch_xy_goal_tolerance: false

  # Forward simulation
  use_dwa: true
  sim_time: 2.0
  sim_granularity: 0.07
  angular_sim_granularity: 0.1
  vx_samples: 15
  vy_samples: 15
  vth_samples: 15

  
  goal_distance_bias: 24
  scaling_speed: 0.7


  # Accelearation and velocity limits
  acc_limit_trans: 10
  acc_lim_x: 10.0
  acc_lim_y: 10.0

  max_trans_vel: 1
  min_trans_vel: 0.4
  max_vel_x: +1
  min_vel_x: -1
  max_vel_y: +1
  min_vel_y: -1
  max_rot_vel: 1.0
  min_rot_vel: 0.4

  # Other
  oscillation_reset_dist: 0.1

  publish_traj_pc: true
  publish_cost_grid_pc: true
  global_frame_id: odom