local_costmap:
  global_frame: odom # Odometry reference link
  robot_base_frame: base_link # Robot link
  
  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 2

  static_map: false # Do not need static map to improve the performance of nav
  rolling_window: true
  width: 4
  height: 4
  resolution: 0.05
