
robot_radius: 0.25  

map_type: voxel

voxel_layer:
  enabled:              true
  max_obstacle_height:  4.2
  origin_z:             0.0
  z_resolution:         0.1
  z_voxels:             22
  unknown_threshold:    15
  mark_threshold:       0
  combination_method:   1
  track_unknown_space:  true    
  obstacle_range: 2.5
  raytrace_range: 3.0
  publish_voxel_map: true
  observation_sources:  scan 
  scan:
    data_type: LaserScan
    topic: scan
    marking: true
    clearing: true
    min_obstacle_height: 0.1
    max_obstacle_height: 3.3


inflation_layer:
  enabled:              true
  cost_scaling_factor:  2.58 
  inflation_radius:     1.0 

static_layer:
  enabled:              true
  
