
shutdown_costmaps: false

controller_frequency: 5.0
controller_patience: 3.0

planner_frequency: 0
planner_patience: 5.0

oscillation_timeout: 5.0
oscillation_distance: 0.2

base_local_planner: "base_local_planner/TrajectoryPlannerROS"

base_global_planner: "navfn/NavfnROS" 

