TebLocalPlannerROS:

 odom_topic: /odom
 odom_frame: odom
 map_frame: map
 
 # Trajectory
 teb_autosize: True
 dt_ref: 0.3
 dt_hysteresis: 0.03
 max_samples: 3
 global_plan_overwrite_orientation: True
 allow_init_with_backwards_motion: True
 max_global_plan_lookahead_dist: 0.7
 global_plan_viapoint_sep: 0.2
 global_plan_prune_distance: 1
 exact_arc_length: False
 feasibility_check_no_poses: 2
 publish_feedback: True
 
 # Robot
 max_vel_x: 1.135
 max_vel_x_backwards: 0.5
 max_vel_y: 1.135  # 允许机器人沿Y轴以此速度移动
 max_vel_theta: 7.0
 acc_lim_y: 9.25  # Y轴加速度限制
 acc_lim_x: 9.25
 acc_lim_theta: 15.15
 holonomic_robot: True  # 全向移动标志设置为True

 footprint_model:
   type: "circular"
   radius: 0.3

 # GoalTolerance
 xy_goal_tolerance: 0.3
 yaw_goal_tolerance: 0.5
 free_goal_vel: False
 complete_global_plan: True
    
 # Obstacles
 min_obstacle_dist: 0.5
 inflation_dist: 0.6
 include_costmap_obstacles: True
 costmap_obstacles_behind_robot_dist: 1.0
 obstacle_poses_affected: 20
 dynamic_obstacle_inflation_dist: 0.6
 include_dynamic_obstacles: True
 costmap_converter_plugin: ""
 costmap_converter_spin_thread: True
 costmap_converter_rate: 8

 # Optimization
 no_inner_iterations: 5
 no_outer_iterations: 4
 optimization_activate: True
 optimization_verbose: False
 penalty_epsilon: 0.1
 obstacle_cost_exponent: 4
 weight_max_vel_y: 10.0  # Y轴最大速度的权重
 weight_max_vel_x: 10.0
 weight_max_vel_theta: 760.0
 weight_acc_lim_x: 100
 weight_acc_lim_theta: 950
 weight_kinematics_nh: 100
 weight_kinematics_forward_drive: 200
 weight_kinematics_turning_radius: 500
 weight_optimaltime: 100
 weight_shortest_path: 0
 weight_obstacle: 100
 weight_inflation: 0.2
 weight_dynamic_obstacle: 10
 weight_dynamic_obstacle_inflation: 0.2
 weight_viapoint: 80
 weight_adapt_factor: 2

 # Homotopy Class Planner
 enable_homotopy_class_planning: False
 enable_multithreading: True
 max_number_classes: 3
 selection_cost_hysteresis: 1.0
 selection_prefer_initial_plan: 0.95
 selection_obst_cost_scale: 1.0
 selection_alternative_time_cost: False
 roadmap_graph_no_samples: 15
 roadmap_graph_area_width: 5
 roadmap_graph_area_length_scale: 1.0
 h_signature_prescaler: 0.5
 h_signature_threshold: 0.1
 obstacle_heading_threshold: 0.45
 switching_blocking_period: 0.0
 viapoints_all_candidates: True
 delete_detours_backwards: True
 max_ratio_detours_duration_best_duration: 3.0
 visualize_hc_graph: False
 visualize_with_time_as_z_axis_scale: False

# Recovery
 shrink_horizon_backup: True
 shrink_horizon_min_duration: 10
 oscillation_recovery: True
 oscillation_v_eps: 0.1
 oscillation_omega_eps: 0.1
 oscillation_recovery_min_duration: 10
 oscillation_filter_duration: 10
