rm_track:
  max_match_distance: 0.1
  max_target_holding_time: 0.1
  max_storage_time: 1
  max_lost_time: 0.1
  num_data: 30
  filters:
    - type: height_filter
      basic_range: [ -0.6, 999.0 ]
      double_check_range: [ 0.5, 1.0 ]
    - type: distance_filter
      basic_range: [ 0., 3.5 ]
      double_check_range: [ 4.0, 6.0 ]
    - type: id_filter
      id: 7
  selectors:
    - type: id_selector
      id: 1
    - type: closest_to_image_center
  linear_kf:
    Q: [ 1000.0, 1000.0, 1000.0, 1000.0, 1000.0, 1000.0 ]
    R: [ 0.01, 0.01, 0.01 ]
