standalone_tags:
  [
    { id: 1, size: 0.095, name: "detection_tag1" },
    { id: 11, size: 0.095, name: "detection_tag2" },
    { id: 21, size: 0.095, name: "detection_tag3" },
    { id: 31, size: 0.095, name: "detection_tag4" },
  ]
