name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: deps
      run: sudo apt-get update && sudo apt-get install -y libboost-all-dev libeigen3-dev
    - name: generate
      run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TYPE=cmake
    - name: make
      run: cd build && make -j
    - name: test
      run: cd build && make test -j
